version: '2'
services:

  mqtt-external-ip:
    build:
      context: .
    restart: always
    container_name: mqtt-external-ip
    command: -mqttBroker ${MQTT_BROKER} -topic ${MQTT_TOPIC} -user ${MQTT_USER} -password ${MQTT_PWD} -period ${PERIOD}
    network_mode: "host"
